version: '3'

services:
  dkc_clientsmanager:
   image: clientsmanager
   ports:
     - 9181
   environment:
     - SERVICE_PORTS=9181
   deploy:
     replicas: 2
     update_config:
       parallelism: 5
       delay: 10s
     restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
   networks:
     - web2

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - dkc_clientsmanager
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 81:80
    networks:
      - web2
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  web2:
    driver: overlay
