version: '3'

services:
  dkc_shoppingcart:
   image: shoppingcart
   ports:
     - 8080
   environment:
     - SERVICE_PORTS=8080
   deploy:
     replicas: 3
     update_config:
       parallelism: 5
       delay: 10s
     restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
   networks:
     - web2

  proxy2:
    image: dockercloud/haproxy
    depends_on:
      - dkc_shoppincart
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 90:80
    networks:
      - web2
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  web2:
    driver: overlay
