version: '3'

services:
  b2c-frontend:
   image: touresbalon/b2c-frontend
   ports:
     - 8080
   environment:
     - SERVICE_PORTS=4200
   deploy:
     replicas: 3
     update_config:
       parallelism: 3
       delay: 10s
     restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
   networks:
     - web

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - b2c-frontend
    environment:
      - BALANCE=roundrobin
      - COOKIE=SRVNAME insert
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 1936:1936
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  web:
    driver: overlay
